//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelierTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemShortName { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> ItemDiscPerc { get; set; }
        public Nullable<System.DateTime> DiscEndDate { get; set; }
        public Nullable<bool> IsMostUsed { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
